const sqlite3 = require('sqlite3').verbose();
const path = require('path');

const db = new sqlite3.Database(path.join(__dirname, 'challenges.db'), (err) => {
    if (err) {
        console.error('Error al conectar a la BD:', err);
        process.exit(1);
    }
    console.log('Conectado a SQLite');
});

const sqlChallenges = [
    // SELECT BÁSICO
    { nombre: "Seleccionar Todas las Columnas", descripcion: "Obtén todos los datos de la tabla estudiantes | Output: Todos los registros con todas las columnas", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);", tags: "SELECT,básico,*" },
    { nombre: "Seleccionar Columna Específica", descripcion: "Obtén solo los nombres de todos los estudiantes | Output: Columna nombre de todos los registros", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT nombre FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "SELECT,columna,específica" },
    { nombre: "Seleccionar Dos Columnas", descripcion: "Obtén nombre y edad de todos los estudiantes | Output: Dos columnas (nombre, edad)", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT nombre, edad FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);", tags: "SELECT,múltiples,columnas" },
    { nombre: "Alias de Columna", descripcion: "Obtén edad renombrada como 'años' | Output: Columna edad con alias 'años'", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT nombre, edad AS años FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "alias,AS,SELECT" },
    { nombre: "Valores Únicos", descripcion: "Obtén todas las ciudades sin duplicados | Output: Lista de ciudades únicas", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT DISTINCT ciudad FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);", tags: "DISTINCT,único,eliminación" },
    { nombre: "Contar Registros", descripcion: "¿Cuántos estudiantes hay en total? | Output: Un número: cantidad total de estudiantes", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT COUNT(*) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);", tags: "COUNT,agregado,total" },
    { nombre: "Contar Columna Específica", descripcion: "¿Cuántos estudiantes tienen edad registrada? | Output: Cantidad de registros con edad no nula", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT COUNT(edad) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "COUNT,nulo,columna" },
    { nombre: "Promedio de Valores", descripcion: "¿Cuál es la edad promedio de los estudiantes? | Output: Un número: promedio de edades", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT AVG(edad) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "AVG,promedio,agregado" },
    { nombre: "Valor Máximo", descripcion: "¿Cuál es la edad máxima registrada? | Output: Un número: edad máxima", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT MAX(edad) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "MAX,máximo,agregado" },
    { nombre: "Valor Mínimo", descripcion: "¿Cuál es la edad mínima registrada? | Output: Un número: edad mínima", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT MIN(edad) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "MIN,mínimo,agregado" },

    // WHERE
    { nombre: "Filtrar por Igualdad", descripcion: "Obtén todos los estudiantes de Madrid | Output: Registros donde ciudad es Madrid", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes WHERE ciudad = 'Madrid';", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);", tags: "WHERE,igualdad,filtro" },
    { nombre: "Filtrar Mayor que", descripcion: "Obtén estudiantes mayores de 18 años | Output: Registros con edad > 18", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes WHERE edad > 18;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "WHERE,comparación,>" },
    { nombre: "Filtrar Menor que", descripcion: "Obtén estudiantes menores de 16 años | Output: Registros con edad < 16", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes WHERE edad < 16;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "WHERE,comparación,<" },
    { nombre: "Filtrar Diferente", descripcion: "Obtén estudiantes que no sean de Barcelona | Output: Registros donde ciudad no es Barcelona", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes WHERE ciudad != 'Barcelona';", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);", tags: "WHERE,!=,diferente" },
    { nombre: "AND Lógico", descripcion: "Obtén estudiantes de Madrid mayores de 20 años | Output: Registros de Madrid con edad > 20", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes WHERE ciudad = 'Madrid' AND edad > 20;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT,\n  ciudad VARCHAR(100)\n);", tags: "AND,lógico,WHERE" },
    { nombre: "OR Lógico", descripcion: "Obtén estudiantes de Madrid o Barcelona | Output: Registros de Madrid o Barcelona", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes WHERE ciudad = 'Madrid' OR ciudad = 'Barcelona';", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);", tags: "OR,lógico,WHERE" },
    { nombre: "IN (Múltiples Valores)", descripcion: "Obtén estudiantes de Madrid, Barcelona o Valencia | Output: Registros de esas 3 ciudades", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes WHERE ciudad IN ('Madrid', 'Barcelona', 'Valencia');", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);", tags: "IN,múltiple,WHERE" },
    { nombre: "BETWEEN (Rango)", descripcion: "Obtén estudiantes entre 18 y 25 años | Output: Registros con 18 ≤ edad ≤ 25", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes WHERE edad BETWEEN 18 AND 25;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "BETWEEN,rango,WHERE" },
    { nombre: "LIKE (Búsqueda Inicio)", descripcion: "Obtén estudiantes cuyo nombre empieza con 'A' | Output: Registros con nombre que inicia con A", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes WHERE nombre LIKE 'A%';", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);", tags: "LIKE,patrón,búsqueda" },
    { nombre: "LIKE (Terminación)", descripcion: "Obtén estudiantes cuyo nombre termina con 'o' | Output: Registros con nombre que termina con o", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes WHERE nombre LIKE '%o';", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);", tags: "LIKE,patrón,búsqueda" },

    // ORDER BY
    { nombre: "Ordenar Ascendente", descripcion: "Obtén estudiantes ordenados por edad (menor a mayor) | Output: Registros ordenados por edad ascendente", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes ORDER BY edad ASC;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "ORDER BY,ASC,ordenamiento" },
    { nombre: "Ordenar Descendente", descripcion: "Obtén estudiantes ordenados por edad (mayor a menor) | Output: Registros ordenados por edad descendente", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes ORDER BY edad DESC;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);", tags: "ORDER BY,DESC,ordenamiento" },
    { nombre: "Ordenar Alfabético", descripcion: "Obtén estudiantes ordenados por nombre alfabéticamente | Output: Registros ordenados por nombre A-Z", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes ORDER BY nombre ASC;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);", tags: "ORDER BY,alfabético,ordenamiento" },
    { nombre: "LIMIT (Primeros N)", descripcion: "Obtén solo los 5 primeros estudiantes | Output: Solo 5 registros", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT * FROM estudiantes LIMIT 5;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nSQL Server:\nSELECT TOP 5 * FROM estudiantes;", tags: "LIMIT,restricción,TOP" },
    { nombre: "TOP N Estudiantes por Edad", descripcion: "Obtén los 3 estudiantes más jóvenes | Output: 3 registros con menor edad", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes ORDER BY edad ASC LIMIT 3;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nSELECT TOP 3 * FROM estudiantes ORDER BY edad ASC;", tags: "ORDER BY,LIMIT,TOP,ordenamiento" },
    { nombre: "Ordenar Múltiples Columnas", descripcion: "Ordenar por ciudad y luego por nombre | Output: Registros ordenados por ciudad y luego por nombre", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes ORDER BY ciudad ASC, nombre ASC;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);", tags: "ORDER BY,múltiple,ordenamiento" },
    { nombre: "OFFSET y LIMIT (Paginación)", descripcion: "Obtén registros 6-10 (segunda página) | Output: 5 registros saltando los 5 primeros", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes LIMIT 5 OFFSET 5;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\n\nSQL Server:\nSELECT * FROM estudiantes OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;", tags: "OFFSET,LIMIT,paginación" },

    // GROUP BY
    { nombre: "Contar por Grupo", descripcion: "¿Cuántos estudiantes hay en cada ciudad? | Output: Filas: ciudad | cantidad", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT ciudad, COUNT(*) FROM estudiantes GROUP BY ciudad;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);", tags: "GROUP BY,COUNT,agregado" },
    { nombre: "Promedio por Grupo", descripcion: "¿Cuál es la edad promedio en cada ciudad? | Output: Filas: ciudad | promedio_edad", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT ciudad, AVG(edad) FROM estudiantes GROUP BY ciudad;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);", tags: "GROUP BY,AVG,agregado" },
    { nombre: "Máximo por Grupo", descripcion: "¿Cuál es la edad máxima en cada ciudad? | Output: Filas: ciudad | edad_máxima", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT ciudad, MAX(edad) FROM estudiantes GROUP BY ciudad;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);", tags: "GROUP BY,MAX,agregado" },
    { nombre: "Mínimo por Grupo", descripcion: "¿Cuál es la edad mínima en cada ciudad? | Output: Filas: ciudad | edad_mínima", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT ciudad, MIN(edad) FROM estudiantes GROUP BY ciudad;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);", tags: "GROUP BY,MIN,agregado" },
    { nombre: "Suma por Grupo", descripcion: "¿Cuál es el total de edad en cada ciudad? | Output: Filas: ciudad | suma_edad", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT ciudad, SUM(edad) FROM estudiantes GROUP BY ciudad;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);", tags: "GROUP BY,SUM,agregado" },
    { nombre: "GROUP BY Múltiples Columnas", descripcion: "Contar estudiantes por ciudad y edad | Output: Filas: ciudad | edad | cantidad", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT ciudad, edad, COUNT(*) FROM estudiantes GROUP BY ciudad, edad;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);", tags: "GROUP BY,múltiple,agregado" },
    { nombre: "HAVING (Filtrar Grupos)", descripcion: "Ciudades con más de 5 estudiantes | Output: Solo ciudades con más de 5 estudiantes", lenguaje: "SQL", complejidad: "Alta", nivel: "Avanzado", solucion: "SELECT ciudad, COUNT(*) FROM estudiantes GROUP BY ciudad HAVING COUNT(*) > 5;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100)\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100)\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100)\n);", tags: "HAVING,GROUP BY,filtro" },
    { nombre: "HAVING con AVG", descripcion: "Ciudades con edad promedio mayor a 25 | Output: Ciudades con promedio > 25", lenguaje: "SQL", complejidad: "Alta", nivel: "Avanzado", solucion: "SELECT ciudad, AVG(edad) FROM estudiantes GROUP BY ciudad HAVING AVG(edad) > 25;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  ciudad VARCHAR(100),\n  edad INT\n);", tags: "HAVING,AVG,filtro" },

    // FECHAS
    { nombre: "Fecha Actual", descripcion: "Obtén la fecha de hoy | Output: La fecha de hoy en formato YYYY-MM-DD", lenguaje: "SQL", complejidad: "Fácil", nivel: "Básico", solucion: "SELECT CURRENT_DATE;", code_schema: "PostgreSQL: SELECT CURRENT_DATE;\nMySQL: SELECT CURDATE();\nSQL Server: SELECT CAST(GETDATE() AS DATE);", tags: "FECHA,CURRENT_DATE,función" },
    { nombre: "Extrae Año", descripcion: "¿En qué año nació cada estudiante? | Output: Filas: nombre | año", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT nombre, EXTRACT(YEAR FROM fecha_nacimiento) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, EXTRACT(YEAR FROM fecha_nacimiento) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, YEAR(fecha_nacimiento) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, YEAR(fecha_nacimiento) FROM estudiantes;", tags: "EXTRACT,YEAR,fecha" },
    { nombre: "Extrae Mes", descripcion: "¿En qué mes nació cada estudiante? | Output: Filas: nombre | mes", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT nombre, EXTRACT(MONTH FROM fecha_nacimiento) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, EXTRACT(MONTH FROM fecha_nacimiento) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, MONTH(fecha_nacimiento) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, MONTH(fecha_nacimiento) FROM estudiantes;", tags: "EXTRACT,MONTH,fecha" },
    { nombre: "Diferencia de Años", descripcion: "¿Cuántos años tiene cada estudiante hoy? | Output: Filas: nombre | edad", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT nombre, EXTRACT(YEAR FROM age(fecha_nacimiento)) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, EXTRACT(YEAR FROM age(fecha_nacimiento)) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, YEAR(CURDATE()) - YEAR(fecha_nacimiento) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT nombre, DATEDIFF(YEAR, fecha_nacimiento, CAST(GETDATE() AS DATE)) FROM estudiantes;", tags: "AGE,DATEDIFF,diferencia" },
    { nombre: "Filtrar por Rango de Fechas", descripcion: "Estudiantes nacidos entre 2000 y 2010 | Output: Registros nacidos entre 2000-2010", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT * FROM estudiantes WHERE fecha_nacimiento BETWEEN '2000-01-01' AND '2010-12-31';", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT * FROM estudiantes WHERE fecha_nacimiento BETWEEN '2000-01-01' AND '2010-12-31';\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT * FROM estudiantes WHERE fecha_nacimiento BETWEEN '2000-01-01' AND '2010-12-31';\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT * FROM estudiantes WHERE fecha_nacimiento BETWEEN '2000-01-01' AND '2010-12-31';", tags: "BETWEEN,fecha,rango" },
    { nombre: "Estudiantes Mayores de Edad", descripcion: "Estudiantes con 18 años o más (nacidos antes de 2006) | Output: Estudiantes con 18+ años", lenguaje: "SQL", complejidad: "Alta", nivel: "Avanzado", solucion: "SELECT * FROM estudiantes WHERE EXTRACT(YEAR FROM age(fecha_nacimiento)) >= 18;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT * FROM estudiantes WHERE EXTRACT(YEAR FROM age(fecha_nacimiento)) >= 18;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT * FROM estudiantes WHERE (YEAR(CURDATE()) - YEAR(fecha_nacimiento)) >= 18;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  fecha_nacimiento DATE\n);\nSELECT * FROM estudiantes WHERE DATEDIFF(YEAR, fecha_nacimiento, CAST(GETDATE() AS DATE)) >= 18;", tags: "AGE,DATEDIFF,comparación" },

    // FUNCIONES AVANZADAS
    { nombre: "CASE WHEN", descripcion: "Clasificar estudiantes por rango de edad | Output: Filas: nombre | clasificación", lenguaje: "SQL", complejidad: "Alta", nivel: "Avanzado", solucion: "SELECT nombre, CASE WHEN edad < 18 THEN 'Menor' WHEN edad >= 18 THEN 'Mayor' END FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\nSELECT nombre, CASE WHEN edad < 18 THEN 'Menor' WHEN edad >= 18 THEN 'Mayor' END FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\nSELECT nombre, CASE WHEN edad < 18 THEN 'Menor' WHEN edad >= 18 THEN 'Mayor' END FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\nSELECT nombre, CASE WHEN edad < 18 THEN 'Menor' WHEN edad >= 18 THEN 'Mayor' END FROM estudiantes;", tags: "CASE,condicional,lógica" },
    { nombre: "CAST (Conversión)", descripcion: "Convertir edad a texto | Output: Edad como texto", lenguaje: "SQL", complejidad: "Alta", nivel: "Avanzado", solucion: "SELECT nombre, CAST(edad AS VARCHAR) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\nSELECT nombre, CAST(edad AS VARCHAR) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\nSELECT nombre, CAST(edad AS CHAR) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  edad INT\n);\nSELECT nombre, CAST(edad AS VARCHAR) FROM estudiantes;", tags: "CAST,conversión,tipo" },
    { nombre: "CONCAT (Concatenación)", descripcion: "Combinar nombre y ciudad en una columna | Output: Filas combinadas: 'nombre - ciudad'", lenguaje: "SQL", complejidad: "Alta", nivel: "Avanzado", solucion: "SELECT CONCAT(nombre, ' - ', ciudad) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\nSELECT CONCAT(nombre, ' - ', ciudad) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\nSELECT CONCAT(nombre, ' - ', ciudad) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100),\n  ciudad VARCHAR(100)\n);\nSELECT nombre + ' - ' + ciudad FROM estudiantes;", tags: "CONCAT,concatenación,string" },
    { nombre: "UPPER (Mayúsculas)", descripcion: "Convertir todos los nombres a mayúsculas | Output: Nombres en mayúsculas", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT UPPER(nombre) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT UPPER(nombre) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT UPPER(nombre) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT UPPER(nombre) FROM estudiantes;", tags: "UPPER,mayúscula,string" },
    { nombre: "LOWER (Minúsculas)", descripcion: "Convertir todos los nombres a minúsculas | Output: Nombres en minúsculas", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT LOWER(nombre) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT LOWER(nombre) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT LOWER(nombre) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT LOWER(nombre) FROM estudiantes;", tags: "LOWER,minúscula,string" },
    { nombre: "LENGTH (Longitud)", descripcion: "¿Cuántos caracteres tiene cada nombre? | Output: Filas: nombre | longitud", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT nombre, LENGTH(nombre) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT nombre, LENGTH(nombre) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT nombre, LENGTH(nombre) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT nombre, LEN(nombre) FROM estudiantes;", tags: "LENGTH,LEN,string" },
    { nombre: "ROUND (Redondear)", descripcion: "Redondear promedio de edad a 2 decimales | Output: Un número redondeado a 2 decimales", lenguaje: "SQL", complejidad: "Media", nivel: "Medio", solucion: "SELECT ROUND(AVG(edad), 2) FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  edad INT\n);\nSELECT ROUND(AVG(edad), 2) FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  edad INT\n);\nSELECT ROUND(AVG(edad), 2) FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  edad INT\n);\nSELECT ROUND(AVG(CAST(edad AS FLOAT)), 2) FROM estudiantes;", tags: "ROUND,redondeo,matemática" },
    { nombre: "COALESCE (NULL Handling)", descripcion: "Mostrar nombre o 'Sin asignar' si es NULL | Output: Nombres o 'Sin asignar' si NULL", lenguaje: "SQL", complejidad: "Alta", nivel: "Avanzado", solucion: "SELECT COALESCE(nombre, 'Sin asignar') FROM estudiantes;", code_schema: "PostgreSQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT COALESCE(nombre, 'Sin asignar') FROM estudiantes;\n\nMySQL:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT COALESCE(nombre, 'Sin asignar') FROM estudiantes;\n\nSQL Server:\nCREATE TABLE estudiantes (\n  id INT PRIMARY KEY,\n  nombre VARCHAR(100)\n);\nSELECT COALESCE(nombre, 'Sin asignar') FROM estudiantes;", tags: "COALESCE,NULL,manejo" }
];

function insertSQLChallenges() {
    db.serialize(() => {
        const stmt = db.prepare(`
            INSERT INTO challenges (nombre_challenge, descripcion_challenge, lenguaje, complejidad, nivel, solucion_challenge, code_schema, tags)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        `);

        sqlChallenges.forEach(challenge => {
            stmt.run(
                challenge.nombre,
                challenge.descripcion,
                challenge.lenguaje,
                challenge.complejidad,
                challenge.nivel,
                challenge.solucion,
                challenge.code_schema,
                challenge.tags,
                (err) => {
                    if (err) {
                        console.error('Error al insertar:', err);
                    }
                }
            );
        });

        stmt.finalize(() => {
            console.log(`✅ Se insertaron ${sqlChallenges.length} challenges SQL exitosamente`);
            db.close(() => {
                console.log('BD cerrada');
                process.exit(0);
            });
        });
    });
}

insertSQLChallenges();
